import 'package:flutter/material.dart';

final Map<String, List<Color>> cardTypeColorsMap = {
  "aktion": [Colors.white],
  "aktion-angriff": [Colors.white],
  "aktion-angriff-pluendern": [Colors.white],
  "aktion-angriff-ritter": [Colors.white],
  "aktion-angriff-punkte": [Colors.white, Colors.green],
  "aktion-dauer": [Colors.deepOrangeAccent],
  "aktion-dauer-angriff": [Colors.deepOrangeAccent],
  "aktion-dauer-reaktion": [Colors.blueAccent, Colors.deepOrangeAccent],
  "aktion-pluendern": [Colors.white],
  "aktion-preis": [Colors.white],
  "aktion-punkte": [Colors.white, Colors.green],
  "aktion-reaktion": [Colors.blueAccent],
  "aktion-ruine": [Colors.brown],
  "aktion-unterschlupf": [Colors.white, Colors.deepOrange],
  "fluch": [Colors.deepPurple],
  "geld": [Colors.orangeAccent],
  "geld-angriff": [Colors.orangeAccent],
  "geld-dauer": [Colors.orangeAccent, Colors.deepOrangeAccent],
  "geld-preis": [Colors.white],
  "geld-punkte": [Colors.orangeAccent, Colors.green],
  "geld-reaktion": [Colors.orangeAccent, Colors.blueAccent],
  "punkte": [Colors.green],
  "punkte-reaktion": [Colors.green, Colors.blueAccent],
  "punkte-unterschlupf": [Colors.green, Colors.deepOrange],
  "reaktion-unterschlupf": [Colors.blueAccent, Colors.deepOrange],
  "unterschlupf": [Colors.white],
};
