import 'package:flutter/material.dart';

const lightBrown = Color(0xffa98e5f);
const lightGrey = Color(0xff969696);
const lightOrange = Color(0xffeab97e);
const lowGreen = Color(0xff437026);

final Map<String, List<Color>> cardTypeColorsMap = {
  "aktion": [Colors.white],
  "aktion-angriff": [Colors.white],
  "aktion-angriff-dauer": [Colors.deepOrangeAccent],
  "aktion-angriff-pluendern": [Colors.white],
  "aktion-angriff-reisender": [Colors.white],
  "aktion-angriff-ritter": [Colors.white],
  "aktion-angriff-punkte": [Colors.white, Colors.green],
  "aktion-angriff-unheil": [Colors.white],
  "aktion-dauer": [Colors.deepOrangeAccent],
  "aktion-dauer-angriff": [Colors.deepOrangeAccent],
  "aktion-dauer-reaktion": [Colors.blueAccent, Colors.deepOrangeAccent],
  "aktion-erscheinung": [Colors.white],
  "aktion-geld": [Colors.white, Colors.orangeAccent],
  "aktion-nacht-angriff-unheil": [Colors.black12, Colors.white],
  "aktion-pluendern": [Colors.white],
  "aktion-preis": [Colors.white],
  "aktion-punkte": [Colors.white, Colors.green],
  "aktion-reaktion": [Colors.blueAccent],
  "aktion-reisender": [Colors.white],
  "aktion-reserve": [lightBrown],
  "aktion-reserve-punkte": [lightBrown, Colors.green],
  "aktion-ruine": [Colors.brown],
  "aktion-sammlung": [Colors.white],
  "aktion-segen": [Colors.white],
  "aktion-unheil": [Colors.white],
  "aktion-unterschlupf": [Colors.white, Colors.deepOrange],
  "aktion-zombie": [Colors.white],
  "befehl-aktion": [Colors.white],
  "ereignis": [lightGrey],
  "fluch": [Colors.deepPurple],
  "gabe": [Colors.amberAccent],
  "geld": [Colors.orangeAccent],
  "geld-angriff": [Colors.orangeAccent],
  "geld-angriff-segen": [Colors.orangeAccent],
  "geld-dauer": [Colors.orangeAccent, Colors.deepOrangeAccent],
  "geld-erbstueck": [Colors.orangeAccent],
  "geld-preis": [Colors.white],
  "geld-punkte": [Colors.orangeAccent, Colors.green],
  "geld-punkte-erbstueck": [Colors.orangeAccent, Colors.green],
  "geld-punkte-schloss": [Colors.orangeAccent, Colors.green],
  "geld-reaktion": [Colors.orangeAccent, Colors.blueAccent],
  "geld-reserve": [Colors.orangeAccent],
  "landmarke": [lowGreen],
  "nacht": [Colors.black12],
  "nacht-angriff-unheil": [Colors.black12],
  "nacht-dauer": [Colors.orangeAccent, Colors.black12],
  "nacht-dauer-angriff": [Colors.orangeAccent, Colors.black12],
  "nacht-dauer-erscheinung": [Colors.orangeAccent, Colors.black12],
  "plage": [Colors.deepPurple],
  "punkte": [Colors.green],
  "punkte-reaktion": [Colors.green, Colors.blueAccent],
  "punkte-schloss": [Colors.green],
  "punkte-unterschlupf": [Colors.green, Colors.deepOrange],
  "reaktion-unterschlupf": [Colors.blueAccent, Colors.deepOrange],
  "unterschlupf": [Colors.white],
  "zustand": [lightOrange],
};
